name: Update OSINT

on:
  workflow_dispatch:

  schedule:
    - cron: "0 6 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run OSINT updater
        run: python scripts/update_osint.py
